#!/bin/sh
cd ~/daten
# d=$(date --rfc-3339=date)
# h=$(date +%s)
#d=$(expr $h - 1672531200)
d=$(date +%y%m%d)
f=~/archiv/easylang/el$d.zip
test -f $f && f=~/archiv/easylang/el{d}x.zip
echo $f
if test -f $f; then
	echo "File exists - overwrite" 
	rm $f
fi
zip -qr $f easylang/apps/ easylang/progs easylang/misc/ easylang/run/ easylang/main/ easylang/native/ easylang/readme.md easylang/vers.txt easylang/mk

