#!/bin/sh
cd ~/daten
# d=$(date --rfc-3339=date)
d=$(expr $(date +%s) - 1672531200)
zip -r ~/archiv/easylang$d.zip easylang/apps/ easylang/misc/ easylang/run/ easylang/ide/ easylang/native/ easylang/readme.md

