#!/bin/sh
cd ~/daten
# d=$(date --rfc-3339=date)
# h=$(date +%s)
#d=$(expr $h - 1672531200)
d=$(date +%y%m%d)
f=~/archiv/easylang$d.zip
test -f $f && f=~/archiv/easylang${d}x.zip
echo $f
if test -f $f; then
	echo "File exists - exit"
	exit 1
fi
zip -qr $f easylang/apps/ easylang/misc/ easylang/run/ easylang/main/ easylang/native/ easylang/readme.md easylang/vers.txt easylang/mk

