#!/bin/sh

n=run
S=`dirname $0`/../main
D=$HOME/.cache/easylang

mkdir -p $D

test ! -e $D/$n && compile=1
h="$S/kfunc.h $S/klib.h $S/klex.h $S/kparse.h $S/../native/kbgr.c $S/kwasm.h $0"
f="$S/kbas.c"
for i in $f $h; do
	test $i -nt $D/$n && compile=1
done

if test $compile; then
	BASE=/opt/homebrew
	rm -f $D/$n
	if test ! -d $BASE/include/SDL3 ||  test ! -d $BASE/include/SDL3_ttf; then
		echo "SDL3 not found"
		echo "$cc -Wall -O2 -D__NOSDL__ -I$S -O $f -lm -o $D/$n"
		cc -Wall -O2 -D__NOSDL__ -I$S -O $f -lm -o $D/$n
	else
		echo $cc -Wall -O2 -D__SDL__ -I$S -I$BASE/include -L$BASE/lib -O $f -lSDL3 -lSDL3_ttf -lm -o $D/$n
		cc -Wall -O2 -D__SDL__ -I$S -I$BASE/include -L$BASE/lib -O $f -lSDL3 -lSDL3_ttf -lm -o $D/$n
	fi
	echo "done" >&2
fi

if test -x $D/$n; then
#	t0=$(date +%s.%2N)
	$D/$n $*
#	echo "$(date +%s.%2N) - $t0" | bc -l
fi

