#!/bin/sh

n=rundbg
S=`dirname $0`/../ide
D=$HOME/.cache/easylang

mkdir -p $D

test ! -e $D/$n && compile=1
h="$S/kafunc.h $S/kalib.h $S/kalex.h $0"
f="$S/kabas.c"
for i in $f $h; do
  test $i -nt $D/$n && compile=1 
done

if test -d /System; then
  if test $compile; then
    rm -f $D/$n
    echo "Compiling easylang debug ..." >&2
    clang -Wall -g -D__NOSDL__ -I$S -O $f -lm -o $D/$n
#    clang -Wall -fsanitize=address -g -D__NOSDL__ -I$S -O $f -lm -o $D/$n
    echo "done" >&2
  fi

  if test -x $D/$n; then
    $D/$n $*
  fi
  exit 0
fi

if test $compile; then
  rm -f $D/$n
  cc=clang
  which $cc >/dev/null || cc=gcc
  echo "Compiling easylang debug (with $cc) ..." >&2

  $cc -Wall -g -D__NOSDL__ -I$S -O $f -lm -o $D/$n
  echo "done" >&2
fi

if test -x $D/$n; then
#	gdb -ex=run --batch --args $D/$n $*
#	valgrind --leak-check=full --show-leak-kinds=all $D/$n $*
	valgrind $D/$n $*
fi

