#!/bin/sh

o=$HOME/out/easylang/show
mkdir -p $o

xcp() {
	test $2 || set $1 $1
	if test  ! -e  $o/$2 -o $1 -nt $o/$2; then
		echo .. $1
		cp -p $1 $o/$2
	fi
}

xcp show.html index.html
xcp easy_tut2.js
cd $o/../apps
for i in easyw.js easyw.wasm easy.js easy_code2.js; do
	xcp $i
done
