#!/bin/sh

#cd $HOME/daten/kabas/apps
cd ../apps

odir=$HOME/out/easylang/run
mkdir -p $odir

exec >$odir/list.html
cat <<xxx
<!doctype html>
<meta charset=utf-8>
<meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>Code runner - apps & games</title>

<style>
body { 
	background:#222; 
	color:#fff;
	max-width:800px;
}
a { color:#fff; }

h3 {background-color:#555;padding:5px;padding-left:12px}
</style>

<h3>Apps & Games</h3>

<script>
window.name = "easylang_games"
var s = []
function inst(id) {
	window.open("./?code=" + encodeURIComponent(s[id]), "_self")
//	window.open(location.origin + "/run/?code=" + encodeURIComponent(s[id]), "_self")
//	window.open(location.origin + "/run/?code=" + encodeURIComponent(s[id]), "easylang_run")
}
xxx

apps="1x1-trainer catch-the-ball hangman learning-clock letter-memory mastermind math-trainer mine-sweeper monster-maze paint piano reaction-test tictactoe"

i=0
for k in $apps; do
	f=$(echo $k | cut -c1 | tr a-z A-Z)
	n=$f$(echo $k | cut -c2- | tr '-' ' ')

	echo -n "s[$i] = \`"
	cat $k.kab
	echo  "\`"
	i=$((i+1))
done


echo "</script>"

i=0
for k in $apps; do
	f=$(echo $k | cut -c1 | tr a-z A-Z)
	n=$f$(echo $k | cut -c2- | tr '-' ' ')

#	echo $k:$f:$n >&2

	echo "<p><a href=javascript:inst($i)>$n</a>"
	i=$((i+1))
done

cat <<xxx
<p>
<h3>Make your own app</h3>
<a href="../ide/">Programming environment</a>
<p>
<hr>
<small>christof.kaser@gmail.com</small>
xxx

